<?php

namespace Site\Bundle\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequirementRepository extends EntityRepository
{
}
