<?php

namespace Site\Bundle\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequirementRepository extends EntityRepository
{

    //需求搜索列表
    public function search($data)
    {
        $qb = $this->createQueryBuilder('i');


        foreach ($data as $field => $value) {

            if (!$this->getClassMetadata()->hasField($field)) {
                continue;
            }
            // like  操他妈的 这需求 产品脑子被驴踢了？
            if (in_array($field, array('keywords','subject', 'description'))) {
//                $qb->andWhere('i.' . $field . ' like ' . ':' . $field)
//                    ->setParameter($field, '%' . $value . '%');
                $qb->andWhere("i.subject like %{$value}% or i.description like %{$value}%");
                continue;
            }

//            // 时间 array
//            if (in_array($field, array('startTime', 'endTime'))) {
//
//                $qb->andWhere('i.' . $field . ' = ' . ':' . $field)
//                    ->setParameter($field, $value['year'].'-'.$value['month'].'-'.$value['day']);
//                continue;
//            }

            $qb->andWhere($qb->expr()->eq('i.' . $field, ':' . $field))
                ->setParameter($field, $value);
        }

       //var_dump( $qb->getQuery()->getParameters());
        return $qb->getQuery()->getResult();
    }
}
