<?php

namespace Company\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findAllByTime($sort = 'desc')
    {

        $sql = 'select u from CompanyBlogBundle:User u  where u.id > :id order by u.createdAt ' . $sort;

        return $this->getEntityManager()
            ->createQuery(
                $sql
            )
            ->setParameter('id', 2)
            ->getResult();

    }
}
